"""added chart column to project layer link

Revision ID: 0ef9d166358c
Revises: d66308c155e0
Create Date: 2024-04-03 11:09:25.810262

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ef9d166358c'
down_revision = 'd66308c155e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_project', sa.Column('charts', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer_project', 'charts', schema='customer')
    # ### end Alembic commands ###
